kind: pipeline
name: default

steps:
- name: test
  image: python:3.8.1-alpine
  commands:
  - set -eux \
    && apk add --no-cache --virtual .build-deps build-base \
        libressl-dev libffi-dev gcc musl-dev python3-dev \
    && pip install --upgrade pip setuptools wheel \    
    && rm -rf /root/.cache/pip
  # - apk add curl
  # - curl --location --request POST 'http://chat.webspro.co/route' --header 'Content-Type:application/json' --data-raw '{"points":[[-74.072090, 4.710989], [-74.090984, 4.638023]],"instructions":false,"calc_points":false}'
  - wget https://www.rapigo.co
  - ls
  - pip install -e ./src
  - pip install -r requirements.txt
  - pytest ./tests
  environment:
    GRAPHHOPPER_API: https://graphhopper.rapigo.co/route