version: '3'

services:
  web:
    build: .
    #command: ["/bin/sh", "-c", "tail -f /dev/null"]
    command: uvicorn estimator.entrypoints:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - 80:8000
    env_file:
      - ./src/.env    